-- =============================================================================
--  Bit & Breakfast - semilla del diccionario de puntuacion
--
--  Los terminos se guardan YA NORMALIZADOS: minusculas, sin acentos y sin
--  signos, porque la busqueda se hace contra titulo_norm y contra el resumen
--  normalizado por lib/texto.php. Por eso aparece "solucion" y no "solución",
--  y "resenas" y no "reseñas".
--
--  Peso positivo (1..10): cuanto mas sube, mas relevante para un director de
--  sistemas hotelero. En el titular cuenta doble; en el resumen, simple.
--  Peso negativo (-1..-5): filtro anti-publirreportaje del apartado 6.4.
--
--  Ejecutar despues de sql/esquema.sql.
-- =============================================================================

SET NAMES utf8mb4;

INSERT INTO diccionario (termino, peso, categoria, activo) VALUES
-- --- Ciberseguridad e incidentes -------------------------------------------
  ('ransomware',                 9, 'ciberseguridad-cumplimiento', 1),
  ('data breach',                9, 'ciberseguridad-cumplimiento', 1),
  ('brecha de datos',            9, 'ciberseguridad-cumplimiento', 1),
  ('ciberataque',                9, 'ciberseguridad-cumplimiento', 1),
  ('cyberattack',                9, 'ciberseguridad-cumplimiento', 1),
  ('filtracion de datos',        8, 'ciberseguridad-cumplimiento', 1),
  ('vulnerabilidad',             8, 'ciberseguridad-cumplimiento', 1),
  ('vulnerability',              8, 'ciberseguridad-cumplimiento', 1),
  ('zero-day',                   8, 'ciberseguridad-cumplimiento', 1),
  ('cve-',                       8, 'ciberseguridad-cumplimiento', 1),
  ('caida del sistema',          7, 'ciberseguridad-cumplimiento', 1),
  ('outage',                     7, 'ciberseguridad-cumplimiento', 1),
  ('exploit',                    6, 'ciberseguridad-cumplimiento', 1),
  ('malware',                    6, 'ciberseguridad-cumplimiento', 1),
  ('phishing',                   6, 'ciberseguridad-cumplimiento', 1),
  ('credenciales robadas',       6, 'ciberseguridad-cumplimiento', 1),
-- --- Normativa y cumplimiento ----------------------------------------------
  ('ses hospedajes',             9, 'ciberseguridad-cumplimiento', 1),
  ('registro de viajeros',       8, 'ciberseguridad-cumplimiento', 1),
  ('pci dss',                    8, 'pagos-fraude', 1),
  ('rgpd',                       8, 'ciberseguridad-cumplimiento', 1),
  ('gdpr',                       8, 'ciberseguridad-cumplimiento', 1),
  ('nis2',                       8, 'ciberseguridad-cumplimiento', 1),
  ('aepd',                       7, 'ciberseguridad-cumplimiento', 1),
  ('antitrust',                  7, 'distribucion-otas', 1),
  ('sentencia',                  6, 'ciberseguridad-cumplimiento', 1),
  ('digital services act',       6, 'distribucion-otas', 1),
  ('digital markets act',        6, 'distribucion-otas', 1),
  ('dora',                       6, 'ciberseguridad-cumplimiento', 1),
  ('multa',                      6, 'ciberseguridad-cumplimiento', 1),
  ('accesibilidad web',          5, 'ciberseguridad-cumplimiento', 1),
  ('tasa turistica',             5, 'inversion-mercado', 1),
-- --- PMS, CRS e integraciones ----------------------------------------------
  ('property management system', 8, 'pms-crs', 1),
  ('pms',                        8, 'pms-crs', 1),
  ('opera cloud',                8, 'pms-crs', 1),
  ('migracion',                  6, 'pms-crs', 1),
  ('central reservation',        6, 'pms-crs', 1),
  ('crs',                        6, 'pms-crs', 1),
  ('interoperabilidad',          6, 'pms-crs', 1),
  ('integracion',                5, 'pms-crs', 1),
  ('api abierta',                6, 'pms-crs', 1),
  ('open api',                   6, 'pms-crs', 1),
  ('fin de soporte',             7, 'pms-crs', 1),
  ('end of life',                7, 'pms-crs', 1),
-- --- Revenue y precios ------------------------------------------------------
  ('revenue management',         7, 'revenue-rms', 1),
  ('rms',                        7, 'revenue-rms', 1),
  ('precios dinamicos',          7, 'revenue-rms', 1),
  ('dynamic pricing',            7, 'revenue-rms', 1),
  ('attribute based selling',    7, 'revenue-rms', 1),
  ('paridad de precios',         6, 'revenue-rms', 1),
  ('rate parity',                6, 'revenue-rms', 1),
  ('forecasting',                6, 'revenue-rms', 1),
  ('revpar',                     5, 'revenue-rms', 1),
  ('upselling',                  5, 'revenue-rms', 1),
-- --- Distribucion y OTAs ----------------------------------------------------
  ('channel manager',            7, 'distribucion-otas', 1),
  ('motor de reservas',          7, 'distribucion-otas', 1),
  ('booking engine',             7, 'distribucion-otas', 1),
  ('metabuscador',               6, 'distribucion-otas', 1),
  ('metasearch',                 6, 'distribucion-otas', 1),
  ('reserva directa',            6, 'distribucion-otas', 1),
  ('direct booking',             6, 'distribucion-otas', 1),
  ('google hotel',               6, 'distribucion-otas', 1),
  ('conectividad',               5, 'distribucion-otas', 1),
  ('comision',                   4, 'distribucion-otas', 1),
-- --- Inteligencia artificial ------------------------------------------------
  ('agente de ia',               8, 'ia-aplicada', 1),
  ('ai agent',                   8, 'ia-aplicada', 1),
  ('inteligencia artificial',    7, 'ia-aplicada', 1),
  ('artificial intelligence',    7, 'ia-aplicada', 1),
  ('ia generativa',              6, 'ia-aplicada', 1),
  ('generative ai',              6, 'ia-aplicada', 1),
  ('machine learning',           6, 'ia-aplicada', 1),
  ('automatizacion',             6, 'ia-aplicada', 1),
  ('chatbot',                    5, 'ia-aplicada', 1),
  ('copilot',                    5, 'ia-aplicada', 1),
-- --- Pagos y fraude ---------------------------------------------------------
  ('tokenizacion',               7, 'pagos-fraude', 1),
  ('tokenization',               7, 'pagos-fraude', 1),
  ('contracargo',                7, 'pagos-fraude', 1),
  ('chargeback',                 7, 'pagos-fraude', 1),
  ('fraude',                     7, 'pagos-fraude', 1),
  ('psd2',                       7, 'pagos-fraude', 1),
  ('tap to pay',                 6, 'pagos-fraude', 1),
  ('pasarela de pago',           6, 'pagos-fraude', 1),
  ('autenticacion reforzada',    6, 'pagos-fraude', 1),
-- --- Experiencia del huesped ------------------------------------------------
  ('llave movil',                7, 'experiencia-huesped', 1),
  ('mobile key',                 7, 'experiencia-huesped', 1),
  ('check-in digital',           6, 'experiencia-huesped', 1),
  ('digital check-in',           6, 'experiencia-huesped', 1),
  ('kiosco',                     5, 'experiencia-huesped', 1),
  ('fidelizacion',               5, 'experiencia-huesped', 1),
  ('loyalty',                    5, 'experiencia-huesped', 1),
  ('resenas',                    5, 'experiencia-huesped', 1),
-- --- Operaciones e IoT ------------------------------------------------------
  ('housekeeping',               6, 'operaciones-iot', 1),
  ('cerradura electronica',      6, 'operaciones-iot', 1),
  ('iot',                        6, 'operaciones-iot', 1),
  ('eficiencia energetica',      5, 'operaciones-iot', 1),
  ('mantenimiento predictivo',   5, 'operaciones-iot', 1),
  ('robot',                      5, 'operaciones-iot', 1),
-- --- Inversion y mercado ----------------------------------------------------
  ('ronda de financiacion',      8, 'inversion-mercado', 1),
  ('funding round',              8, 'inversion-mercado', 1),
  ('adquisicion',                8, 'inversion-mercado', 1),
  ('acquisition',                8, 'inversion-mercado', 1),
  ('serie a',                    7, 'inversion-mercado', 1),
  ('series a',                   7, 'inversion-mercado', 1),
  ('fusion',                     7, 'inversion-mercado', 1),
  ('salida a bolsa',             7, 'inversion-mercado', 1),
  ('ipo',                        7, 'inversion-mercado', 1),
  ('quiebra',                    7, 'inversion-mercado', 1),
  ('despidos',                   6, 'inversion-mercado', 1),
  ('layoffs',                    6, 'inversion-mercado', 1),
-- --- Madurez del producto ---------------------------------------------------
  ('disponibilidad general',     7, 'tecnologia-general', 1),
  ('general availability',       7, 'tecnologia-general', 1),
  ('implantacion',               7, 'tecnologia-general', 1),
  ('caso de exito',              6, 'tecnologia-general', 1),
  ('piloto',                     6, 'tecnologia-general', 1),
  ('despliegue',                 6, 'tecnologia-general', 1),
  ('rollout',                    6, 'tecnologia-general', 1),
  ('lanzamiento',                5, 'tecnologia-general', 1),
  ('beta',                       4, 'tecnologia-general', 1),
-- --- Filtro anti-publirreportaje (pesos negativos) --------------------------
  ('lider mundial',             -5, '', 1),
  ('world leader',              -5, '', 1),
  ('revoluciona',               -5, '', 1),
  ('revolutionary',             -5, '', 1),
  ('se complace en anunciar',   -5, '', 1),
  ('is pleased to announce',    -5, '', 1),
  ('thrilled to announce',      -5, '', 1),
  ('solucion de vanguardia',    -5, '', 1),
  ('game-changer',              -5, '', 1),
  ('unlock the power',          -5, '', 1),
  ('socio estrategico',         -4, '', 1),
  ('strategic partner',         -4, '', 1),
  ('cutting-edge',              -4, '', 1),
  ('state-of-the-art',          -4, '', 1),
  ('best-in-class',             -4, '', 1),
  ('proud to announce',         -4, '', 1),
  ('sinergia',                  -4, '', 1),
  ('next-generation',           -3, '', 1),
  ('seamless',                  -3, '', 1),
  ('transformador',             -3, '', 1);
